### ISSUE TITLE
Documentation incomplete

### ISSUE THREAD

**Issue by V1RE** [jascha030/wp-sequoia#1]
Could you add a readme.txt or alternatively, a Google docs like this [document](https://docs.google.com/document/d/1K0fW07p-_MtDYaimcfwmqcgYurYKN_MJvA_U7v8hpVU/edit?usp=sharing)

**Comment by jascha030** [comment]
### Wow, 

**such advice**, _very responsibility_.

**Comment by jascha030** [comment]
Shit I accidentally wrote a README in markdown, I hope this will suffice. 

¯\_(ツ)_/¯
